---
services:

  mynetest:
    profiles: ["minetest-adjusted"]
    build:
      dockerfile: luanti-boot-image/Dockerfile
    image: mynetest
    container_name: mynetest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - "CLI_ARGS=--gameid mineclonia"
    volumes:
      - ./instance-data/luanti-data:/config/.minetest
    ports:
      - 30000:30000/udp
    #restart: unless-stopped
    depends_on:
      - postgres

  luanti-bare:
    container_name: luanti-bare
    image: lscr.io/linuxserver/minetest:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      #CLI_ARGS: "--gameid devtest"   ## This worked, created a world.
      #CLI_ARGS: "--gameid mineclonia --migrate postgres"  ## Nope.
      CLI_ARGS: "--gameid mineclonia --worldname world3"
      ## Does not work:
      ## --pgsql_connection 'host=postgres-for-luanti port=5432 user=postgres password=postgres dbname=postgres' 
      ## Needs to be set in the world.mt file as pgsql_connection = host=postgres-for-luanti ...
    volumes:
      - ./instance-data/luanti-data:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: no
    depends_on:
      - postgres


  postgres:
    container_name: postgres-for-luanti
    #image: postgres:17
    image: postgres-chowned:latest
    build:
      dockerfile: postgresql-stuff/postgres-chowned.dockerfile
    environment:
      #- POSTGRES_PASSWORD=minetest-pass
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      #POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd ## See Docker manager passwords.
    volumes:
      - ./instance-data/postgres-data:/var/lib/postgresql/data
      - ./postgresql-stuff/postgres-listenAll.conf:/etc/postgresql/postgresql.conf
      #- ./postgres-passwd.txt:/postgres-passwd.txt
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 10
    shm_size: 128mb
    

## Not used yet.
x-shared-minetest:
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - "CLI_ARGS=--gameid devtest" #optional
  volumes:
    - ./minetest-data:/config/.minetest
  ports:
    - 30000:30000/udp
  restart: unless-stopped
  depends_on:
    - postgres
