FROM ondrejzizka/luanti-mineclonia:latest

## This actually needs to be applied in the mounted volume, before booting the server.
#RUN sed -i 's#^backend = .+#backend = postgresql#' /config/.minetest/worlds/world/world.mt
#RUN echo 'pgsql_connection=user=postgres dbname=postgres' >> /config/.minetest/worlds/world/world.mt
